//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_smart_door_sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ep_Table
    {
        public int ep_Id { get; set; }
        public string ep_Name { get; set; }
        public string ep_Img { get; set; }
        public Nullable<System.DateTime> ep_Inday { get; set; }
    }
}
